# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeigen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=10)),
                ('nachname', models.CharField(max_length=10)),
                ('telnu', models.CharField(max_length=11)),
                ('gastnu', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('re_date', models.DateTimeField()),
            ],
        ),
    ]
